### ISSUE TITLE
Wrong user interface?

### ISSUE THREAD

**Issue by lukaskratzel** [corbado/corbado-nodejs#25]
The return value of `await sdk.sessions().getCurrentUser(jwt);` has a form, that doesn't match the User interface. This is an example return value:
```
User {
  authenticated: false,
  id: '',
  name: '',
  email: '',
  phoneNumber: ''
}
```

**Comment by incorbador** [comment]
user is not an interface but a class. Maybe an old version of node-sdk (pre v2) has been used to test here => I also saw a change in the wizard markdowns that supports that theory :)

I think there is no problem here, getCurrentUser just returns a User object (and that does of course not comply to that interface)
