### ISSUE TITLE
improve the Node.js SDK

### ISSUE THREAD

**Issue by bexxley** [corbado/corbado-nodejs#3]
- [x] Best Practices allgemein für eine Node.js / Express.js SDK
- [ ] Wie können wir testen und Code Coverage (allgemein diese ganzen Badges, die man kennt von anderen) hinzufügen
- [x] Wie müssen wir die Readme verbessern (hier auch schauen, was möglich ist)
- [ ] anschließend dann bitte einen neuen Branch / PR erstellen, wo die BDPs alle eingearbeitet sind
- [x] Mittlerweile haben wir Corbado bei npm auf eine Organisation (anstatt normalen Account) umgestellt. D.h. es könnte sein, dass man ein "@" vor "@corbado/<package-name> benötigt, damit es funktioniert. Bin mir hier allerdings nicht zu 100% sicher, daher bitte überprüfen.

**Comment by vincentdelitz** [comment]
@bexxley kurzes Update. Habe vieles umgebaut, allerdings ist das Thema mit Tests noch offen.

**Comment by vincentdelitz** [comment]
@bexxley gerne hier auch nochmal das Testing anschauen (mittlerweile ist das SDK relativ stable in der Grundstruktur)
